"use client";

import { AppInfo } from "@/components/AppInfo";
import { useLogStore } from "@/store/useLogStore";

export default function Home() {
  const { selectedLog, logFiles } = useLogStore();

  return (
    <div className="flex flex-col items-center p-4 md:p-8">
      <main className="w-full max-w-6xl flex flex-col items-start gap-8">
        <div className="flex items-center justify-between w-full">
          <h1 className="text-3xl font-bold tracking-tight text-black dark:text-white">
            Dashboard
          </h1>
        </div>

        <div className="w-full grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-auto">
          {/* App Info View (Order: -1) */}
          <div className="col-span-1 md:col-span-3">
            <AppInfo />
          </div>

          {/* Other views will go here */}
          {!selectedLog ? (
            <div className="col-span-1 md:col-span-3 p-12 border-2 border-dashed rounded-xl flex flex-col items-center justify-center text-muted-foreground bg-zinc-50 dark:bg-zinc-900/50">
              {logFiles.length === 0 ? (
                <>
                  <p className="text-lg">需要挂载日志文件到app/logs目录下</p>
                  <p className="text-sm opacity-60">请检查 logs 目录是否存在且包含日志文件</p>
                </>
              ) : (
                <>
                  <p className="text-lg">Please select a log file to start analysis</p>
                  <p className="text-sm opacity-60">You can select a file from the top right dropdown</p>
                </>
              )}
            </div>
          ) : (
            <>
              {/* Placeholder for custom views */}
              <div className="col-span-1 p-8 border rounded-lg bg-zinc-50 dark:bg-zinc-900/50 flex items-center justify-center border-dashed">
                <p className="text-sm text-muted-foreground italic text-center">
                  Custom views generated by AI will appear here
                </p>
              </div>
            </>
          )}
        </div>
      </main>
    </div>
  );
}
